enum ErrorCode {
  INCORRECT_PASSWORD = 'INCORRECT_PASSWORD',
  INCORRECT_EMAIL = 'INCORRECT_EMAIL',
  READER_WITH_EMAIL_ALREADY_EXISTS = 'READER_WITH_EMAIL_ALREADY_EXISTS',
  READER_DOES_NOT_EXIST = 'READER_DOES_NOT_EXIST',
  EMAIL_VERIFICATION_FAILED = 'EMAIL_VERIFICATION_FAILED',
  READER_ALREADY_HAS_ACCESS = 'READER_ALREADY_HAS_ACCESS',
  ARTICLE_HAS_BEEN_ALREADY_ADDED_TO_READ = 'ARTICLE_HAS_BEEN_ALREADY_ADDED_TO_READ',
  LACK_OF_ARTICLE_IN_TO_READ = 'LACK_OF_ARTICLE_IN_TO_READ',
  ARTICLE_DOES_NOT_EXIST = 'ARTICLE_DOES_NOT_EXIST',
  ARTICLE_HAS_BEEN_ALREADY_ADDED_READED = 'ARTICLE_HAS_BEEN_ALREADY_ADDED_READED',
  LACK_OF_ARTICLE_IN_READED = 'LACK_OF_ARTICLE_IN_READED',
  REGION_ALEADY_FOLLOWED = 'REGION_ALEADY_FOLLOWED',
  LACK_OF_REGION_IN_FOLLOWED = 'LACK_OF_REGION_IN_FOLLOWED',
  REGION_DOES_NOT_EXIST = 'REGION_DOES_NOT_EXIST',
}

export default ErrorCode;
