enum ErrorCode {
  INCORRECT_PASSWORD = 'INCORRECT_PASSWORD',
  INCORRECT_EMAIL = 'INCORRECT_EMAIL',
  READER_WITH_EMAIL_ALREADY_EXISTS = 'READER_WITH_EMAIL_ALREADY_EXISTS',
  READER_DOES_NOT_EXIST = 'READER_DOES_NOT_EXIST',
  EMAIL_VERIFICATION_FAILED = 'EMAIL_VERIFICATION_FAILED',
}

export default ErrorCode;
