name: Staging

on:
  push:
    branches: [staging]

jobs:
  build_and_deploy_staging:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: envs
        run: echo ${{ secrets.REMOTE_HOST }}